export interface WasmBoyPublicApi {
  config(options?: unknown, canvasElement?: HTMLCanvasElement): Promise<void>;
  getCoreType(): unknown;
  getConfig(): unknown;
  setCanvas(canvasElement: HTMLCanvasElement): Promise<void>;
  getCanvas(): HTMLCanvasElement | undefined;
  addBootROM(type: string, file: ArrayBuffer): Promise<void>;
  getBootROMs(): Promise<unknown[]>;
  loadROM(rom: ArrayBuffer | Uint8Array): Promise<void>;
  play(): Promise<void>;
  pause(): Promise<void>;
  reset(options?: unknown): Promise<void>;
  addPlugin(plugin: unknown): void;
  isPlaying(): boolean;
  isPaused(): boolean;
  isReady(): boolean;
  whenReady(): Promise<void>;
  whenPlaying(): Promise<void>;
  whenPaused(): Promise<void>;
  isLoadedAndStarted(): boolean;
  getVersion(): string;
  getSavedMemory(): Promise<unknown[]>;
  saveLoadedCartridge(additionalInfo?: Record<string, unknown>): Promise<unknown>;
  deleteSavedCartridge(cartridge: unknown): Promise<void>;
  saveState(): Promise<unknown>;
  getSaveStates(): Promise<unknown[]>;
  loadState(state: unknown): Promise<void>;
  deleteState(state: unknown): Promise<void>;
  getFPS(): number;
  setSpeed(speed: number): void;
  isGBC(): Promise<boolean>;
  ResponsiveGamepad: unknown;
  enableDefaultJoypad(): void;
  disableDefaultJoypad(): void;
  setJoypadState(state: unknown): void;
  resumeAudioContext(): void;
  _getAudioChannels(): unknown;
  _getCartridgeInfo(): unknown;
  _getCartridgeRam(): Promise<Uint8Array>;
  getWRAM(): Promise<Uint8Array>;
  setWRAM(payload: Uint8Array): Promise<void>;
  getWorkRAM(): Promise<Uint8Array>;
  setWorkRAM(payload: Uint8Array): Promise<void>;
  writeRAM(address: number, payload: Uint8Array): Promise<boolean>;
  getFullMemory(): Promise<Uint8Array>;
  readMemory(address: number, length: number): Promise<Uint8Array>;
  _runNumberOfFrames(...args: readonly unknown[]): unknown;
  _runWasmExport(name: string, parameters?: readonly number[]): Promise<number>;
  _getWasmMemorySection(start: number, end: number): Promise<Uint8Array>;
  _setWasmMemorySection(start: number, data: Uint8Array | ArrayBuffer): Promise<boolean>;
  setWasmMemorySection(start: number, data: Uint8Array | ArrayBuffer): Promise<boolean>;
  _getWasmConstant(name: string): Promise<number>;
  _getPpuSnapshotBuffer(): Promise<ArrayBuffer | null>;
  _parsePpuSnapshotBuffer(buffer: ArrayBuffer): unknown;
  _getStepsAsString(): string;
  _getCyclesAsString(): string;
  setMemoryBreakpoint(address: number): void;
  clearMemoryBreakpoint(address: number): void;
  clearAllMemoryBreakpoints(): void;
  getBackgroundMapImage(): Uint8ClampedArray;
  getTileDataImage(): Uint8ClampedArray;
  getOamSpritesImage(): Uint8ClampedArray;
  getCPURegisters(): unknown;
  getTimerState(): unknown;
  getLCDState(): unknown;
  getScanlineParameters(): unknown;
}

export const WasmBoy: WasmBoyPublicApi;
