export const HEADLESS_FRAME_WIDTH = 160;
export const HEADLESS_FRAME_HEIGHT = 144;
export const HEADLESS_FRAME_RGBA_CHANNELS = 4;
export const HEADLESS_FRAME_BUFFER_RGBA_SIZE = HEADLESS_FRAME_WIDTH * HEADLESS_FRAME_HEIGHT * HEADLESS_FRAME_RGBA_CHANNELS;

export const HEADLESS_ROM_MAX_BYTES = 0x200000;
export const HEADLESS_CARTRIDGE_RAM_MAX_BYTES = 0x20000;
export const HEADLESS_GAMEBOY_ADDRESS_MIN = 0x0000;
export const HEADLESS_GAMEBOY_ADDRESS_MAX = 0xffff;
export const HEADLESS_BYTE_MASK = 0xff;

export const HEADLESS_SCHEMA_VERSION = 'WasmBoyHeadless';

export const HEADLESS_BUTTON_INDEX = {
  UP: 0,
  RIGHT: 1,
  DOWN: 2,
  LEFT: 3,
  A: 4,
  B: 5,
  SELECT: 6,
  START: 7,
};
